/* Lab Question  (Test 2)
 * 
 * A bottom-up approach is typically used in OOP languages. This is the general design approach that has been used
 * for this software. Do you think it would have been easier or harder to approach this project using a top-down approach?
 * Why do you think a bottom up approach is generally more natural when using OOP languages?
 *
 */

using System;
using System.Collections.Generic;

using Psim.ModelComponents;
using Psim.Materials;

namespace Psim
{
	// Model is comprised of a single material. Hardcoding the time step & number of phonons for now.
	class Model
	{
		// Making parts public for testing purposes

		private const double TIME_STEP = 5e-12;
		private const int NUM_PHONONS = 10000000;
		private Material material;
		public List<Cell> cells = new List<Cell>();
		private List<Sensor> sensors = new List<Sensor>();
		private readonly double highTemp;
		private readonly double lowTemp;
		private readonly double simTime;
		private readonly double tEq;

		public Model(Material material, double highTemp, double lowTemp, double simTime)
		{
			this.material = material;
			this.highTemp = highTemp;
			this.lowTemp = lowTemp;
			this.simTime = simTime;
			tEq = (highTemp + lowTemp) / 2;
		}

		public void AddSensor(int sensorID, double initTemp)
		{
			foreach(var sensor in sensors)
            {
				if (sensorID == sensor.ID)
					throw new ArgumentException($"Sensor ID: {sensorID} is not unique.");
            }

			sensors.Add(new Sensor(sensorID, material, initTemp));
		}

		public void AddCell(double length, double width, int sensorID)
        {
			cells.Add(new Cell(length, width, sensors[sensorID]));
        }

		// TODO: Write a method to add a sensor to the model
		// TODO: Write a method to add a cell to the model

		/// <summary>
		/// Automatically sets all the surfaces in the cells that constitute this model.
		/// Should be called after all the cells have been added
		/// </summary>
		/// <param name="tEq">The equilibrium temperature of the system</param>
		public void SetSurfaces(double tEq)
		{
			int numCells = cells.Count;
			if (numCells < 2)
			{
				throw new InvalidCellCount();
			}

			cells[0].SetEmitSurface(SurfaceLocation.left, highTemp);
			cells[0].SetTransitionSurface(SurfaceLocation.right, cells[1]);
			for (int i = 1; i < numCells - 1; ++i)
			{
				cells[i].SetTransitionSurface(SurfaceLocation.left, cells[i - 1]);
				cells[i].SetTransitionSurface(SurfaceLocation.right, cells[i + 1]);
			}
			cells[^1].SetEmitSurface(SurfaceLocation.right, lowTemp);
			cells[^1].SetTransitionSurface(SurfaceLocation.left, cells[numCells - 2]);
		}

		/// <summary>
		/// Calibrates the emitting surfaces in the model.
		/// </summary>
		/// <param name="tEq">System equilibrium temperature</param>
		/// <param name="effEnergy">Phonon packet effective energy</param>
		/// <param name="timeStep">Simulation time step</param>
		public void SetEmitPhonons(double tEq, double effEnergy, double timeStep)
		{
			foreach (var cell in cells)
			{
				cell.SetEmitPhonons(tEq, effEnergy, timeStep);
			}
		}

		/// <summary>
		/// Returns the total energy of the model (initial energy + emit energy)
		/// </summary>
		/// <returns>Total energy generated by the model over the course of the simulation</returns>
		private double GetTotalEnergy()
		{
			double emitEnergy = 0;
			foreach(var cell in cells)
            {
				emitEnergy += cell.EmitEnergy(tEq, simTime) + cell.InitEnergy(tEq);
            }
			return emitEnergy;
		}

		class InvalidCellCount : Exception
		{
			public InvalidCellCount() { }
			public InvalidCellCount(string description = "") : base(String.Format("Invalid Cell Count {0}", description)) { } 
		}
        public override string ToString()
        {
			string output = "Sensor\tID\tInitTemp\n";

            for (int i = 0; i < sensors.Count; i++)
            {
				output += $"{i}\t{sensors[i].ID}\t{sensors[i].InitTemp}\n";
            }

			output += "\n------Cell Surfaces------\n";

            for (int i = 0; i < cells.Count; i++)
            {
				output += $"L: {cells[i].GetSurface(SurfaceLocation.left)}\t" +
					      $"T: {cells[i].GetSurface(SurfaceLocation.top)}\t" +
					      $"R: {cells[i].GetSurface(SurfaceLocation.right)}\t" +
					      $"B: {cells[i].GetSurface(SurfaceLocation.bot)}\n";
            }
			return output;
        }
    }
}
